### ISSUE TITLE
Pengerjaan UI Login

### ISSUE THREAD

**Issue by goingtoprofandy** [pos-apps/web-toko#14]
Pada task ini, harap berpatokan pada design wireframe yang ada pada task https://github.com/pos-apps/web-toko/issues/7 untuk bentuk tampilannya.
## Requirement
- [ ] Harap menggunakan react js + bootstrap 4
- [ ] Untuk komunikasi data akan menggunakan rest api. kebetulan rest api yang digunakan adalah express js.
## Tasks
- [ ] Buatkan design form login, yang berisikan username/email, password, dan remember me sesuai dengan wireframe
- [ ] Buatkan link untuk reset password sesuai dengan wireframe yang nantinya akan menampilkan popup form untuk mengisi username/email dan nomor hp
